apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: vidocker07/lateshipment:latest
        ports:
        - containerPort: 8080 
        env:
        - name: MYSQL_HOST
          value: "172.31.40.156"
        - name: MYSQL_DATABASE
          value: "Emp_db"
        - name: MYSQL_USER
          value: "devopsteam"
        - name: MYSQL_PASSWORD
          value: "root"
