apiVersion: apps/v1
kind: Deployment
metadata:
  name: Project-Deployment-Infoane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: lateshipment-container
        image: vidocker07/lateshipment:latest
        ports:
        - containerPort: 8080
